parameters:

    paypal_web_checkout.api_endpoint: https://www.paypal.com/cgi-bin/webscr
    paypal_web_checkout.controller.route.name: "paypal_web_checkout_execute"
    paypal_web_checkout.routes.loader.class: "PaymentSuite\\PaypalWebCheckoutBundle\\Router\\PaypalWebCheckoutRoutesLoader"
    paypal_web_checkout.wrapper.class: "PaymentSuite\\PaypalWebCheckoutBundle\\Services\\Wrapper\\PaypalFormTypeWrapper"
    paypal_web_checkout.manager.class: "PaymentSuite\\PaypalWebCheckoutBundle\\Services\\PaypalWebCheckoutManager"
